### ISSUE TITLE
Filter Opportunity Function Incorrect Output W/ 0 filters

### ISSUE THREAD

**Issue by abidtalukder** [LabConnect-RCOS/LabConnect-Backend#173]
**Describe the bug**
With 0 filters, the function should work like a normal getOpportunity type function and should return the max amount of opportunities (within pagination or other limits), but it only returned 1 opportunity

**To Reproduce**
Apply the following filters:
Min pay set to 0
max pay set to 100000 etc.
departments set to []
majors set to []

Input and output shown in screenshot
<img width="342" alt="Labconnect filter failure" src="https://github.com/user-attachments/assets/0763137b-2a96-44eb-9362-25b47eb5af5e">

**Comment by RafaelCenzano** [comment]
#187
