### ISSUE TITLE
Querying for Professors

### ISSUE THREAD

**Issue by SabreBirdOne** [LabConnect-RCOS/LabConnect-Backend#25]
Users may want to look for lab runners. By knowing lab runners, the system can then query related information: like RPI departments, contact information. 

**To do list**
Find lab runners' rcs_id based on attributes: name
Find lab runners' rcs_id based on related tables: 
- Departments that lab runners are part of (given their rcs_ids)
- Lab runners that promote opportunities with specific IDs

**Comments**
This is a small issue. If you plan on resolving many smaller issues in a single branch, please coordinate carefully with the rest of the team.

**Comment by RafaelCenzano** [comment]
#59
