### ISSUE TITLE
Querying for RPI Departments

### ISSUE THREAD

**Issue by SabreBirdOne** [LabConnect-RCOS/LabConnect-Backend#26]
Users and our system may want to know about RPI departments. This issue tackles querying related to the RPI departments table. 

**To do list**
Find RPI department names for departments that a set of lab runners (rcs_id) is part of 
Find RPI department names based on table attribute "description" (very hard - not required to complete issue): description may contain natural language data, so maybe a language model is helpful here.

**Comments**
This is a small issue. If you plan on resolving many smaller issues in a single branch, please coordinate carefully with the rest of the team.

**Comment by RafaelCenzano** [comment]
Completed with #107
