### ISSUE TITLE
Displaying opportunities data from the database on the webpage

### ISSUE THREAD

**Issue by athalm** [LabConnect-RCOS/LabConnect-Backend#44]
Data from the database must be displayed on the webpage.
The fields that are empty for a particular opportunity should not be displayed on the webpage.
For testing , we are using db_test.py

**Comment by swadekar** [comment]
- Display data from the database on the webpage.
- Exclude empty fields for a particular opportunity from being shown on the webpage.
- Utilize the db_test.py file for testing.
- Testing aims to ensure proper handling of empty fields when displaying data.
- Verify that the webpage functions as intended, providing a seamless user experience.

**Comment by RafaelCenzano** [comment]
@abidtalukder completed on frontend
